# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content_title', models.CharField(max_length=100, verbose_name='Заголовок контента')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('image', mezzanine.core.fields.FileField(max_length=255, verbose_name='Изображение')),
                ('image_mobile', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Изображение mobile')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_list', to='pages.Page', verbose_name='Слайдер')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ('_order',),
            },
        ),
    ]
