# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-04 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_auto_20180304_1008'),
        ('content_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Показывается на странице, если не выбрано, будет показан случайный сотрудник', null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Person', verbose_name='Сотрудник'),
        ),
    ]
