# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-04 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0002_homepage_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='person_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст на сотруднике'),
        ),
    ]
