# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Разрешить комментарии'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='photo',
            field=mezzanine.core.fields.FileField(help_text='Пропорционально 1000x300', max_length=255, verbose_name='Фото'),
        ),
    ]
