# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-04 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['name'], 'verbose_name': 'Разряд', 'verbose_name_plural': 'Разряды'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
