# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-04 10:55
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_auto_20180304_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='content',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Тескт'),
            preserve_default=False,
        ),
    ]
