# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_auto_20180304_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.PositiveIntegerField(choices=[(0, 'Тренер'), (10, 'Спортсмен'), (20, 'Президент федерации'), (30, 'Вице президент федерации')], default=0, verbose_name='Должность'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
