# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-06 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0006_person_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
    ]
